openapi: 3.0.3
info:
  title: Swagger Bank Kata - OpenAPI 3.0
  description: |-
    This is a specification of the bank kata repository
  version: "v1"
paths:
  /deposit:
    post:
      tags:
        - bank
      summary: Add a deposit operation of the amount received in the body
      description: Add a deposit operation of the amount received in the body
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amount'
        required: true
      responses:
        '201':
          description: Successful operation
  /withdraw:
    post:
      tags:
        - bank
      summary: Charges the amount received in the body
      description: Charges the amount received in the body
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amount'
        required: true
      responses:
        '201':
          description: Successful operation
  /transactions:
    get:
      tags:
        - bank
      summary: fetches all transactions (no pagination)
      description: fetches all transactions (no pagination)
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
components:
  schemas:
    Amount:
      type: object
      properties:
        amount:
          type: integer
          format: int64
          example: 100000
    Transaction:
      type: object
      properties:
        amount:
          type: integer
          format: int64
          example: 100000
        date:
          type: string
          example: 14/01/2012
        balance:
          type: integer
          format: int64
          example: 6400
    Transactions:
      type: object
      properties:
        amount:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
